name: school_project_ibdb
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  #state management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  #Firebase
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_database: ^9.0.11
  #network
  dio: ^4.0.4

  flutter:
    sdk: flutter
  #Google
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  #Utility
  kartal: ^2.3.1
  image_picker: ^0.8.4+11

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sign_in/IBDb-logos.jpeg
    - assets/sign_in/IBDb-logos_transparent.png
    - assets/sign_in/
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
